name: test-deploy

# Run on each push to master
on:
  push:
    branches: [ master ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing private usage
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: redoc-cli test
        uses: ./ # Uses an action in the root directory
        with:
          args: 'bundle test/petstore.yml -o public/index.html'

      - name: check result
        run: |
          ls -al
          test -f public/index.html || (echo "Missing petstore.html from previous step." && exit 1)
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  test_job_2:
    runs-on: ubuntu-latest
    name: Testing public name
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle test/petstore.yml -o petstore.html'

      - name: check result
        run: |
          ls -al
          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
